function siteHeader(active='Home'){
const links=[['Home','index.html'],['Shop','shop.html'],['Collections','collections.html'],['Installations','installations.html'],['About','about.html'],['Contact','contact.html']];
return `<div class="bg-berry text-white text-[11px] sm:text-xs"><div class="max-w-7xl mx-auto px-4 py-2.5 flex justify-center"><span class="inline-flex items-center gap-2"><i data-lucide="sparkles" class="size-3.5 text-champagne"></i> Premium hair <span class="opacity-40">•</span><i data-lucide="truck" class="size-3.5 text-champagne"></i> Nationwide delivery <span class="opacity-40">•</span><i data-lucide="map-pin" class="size-3.5 text-champagne"></i> George installations</span></div></div>
<header class="sticky top-0 z-50 bg-white/90 backdrop-blur-xl border-b border-rose/70"><div class="max-w-7xl mx-auto px-4 sm:px-6 h-[72px] flex items-center justify-between gap-4"><a href="index.html" class="shrink-0"><span class="display text-xl sm:text-2xl font-bold">Hair by <i class="text-pink">Sentle</i></span></a><nav class="hidden lg:flex items-center gap-7 text-sm font-semibold text-ink/70">${links.map(([n,u])=>`<a href="${u}" class="relative py-2 transition hover:text-pink ${active===n?'text-berry after:absolute after:left-0 after:right-0 after:-bottom-0.5 after:h-0.5 after:bg-pink':''}">${n}</a>`).join('')}</nav><div class="flex items-center gap-2"><a href="login.html" aria-label="Account" class="hidden sm:grid place-items-center size-10 rounded-full hover:bg-blush transition"><i data-lucide="user-round" class="size-[18px]"></i></a><a href="shop.html" aria-label="Search" class="hidden sm:grid place-items-center size-10 rounded-full hover:bg-blush transition"><i data-lucide="search" class="size-[18px]"></i></a><button data-cart-open aria-label="Shopping bag" class="relative grid place-items-center size-10 rounded-full bg-berry text-white hover:bg-pink transition"><i data-lucide="shopping-bag" class="size-[18px]"></i><span data-cart-count class="absolute -top-1 -right-1 size-5 rounded-full bg-pink text-[10px] grid place-items-center font-bold">0</span></button><button data-menu-open aria-label="Open menu" class="lg:hidden grid place-items-center size-10 rounded-full border border-rose"><i data-lucide="menu" class="size-[19px]"></i></button></div></div></header>
<div id="mobileMenu" class="mobile-menu hidden fixed inset-0 z-[70] bg-black/30"><div class="mobile-menu-panel w-[86%] max-w-sm h-full bg-white p-6 shadow-2xl"><div class="flex items-center justify-between"><span class="display text-2xl font-bold">Hair by <i class="text-pink">Sentle</i></span><button data-menu-close class="size-10 rounded-full bg-blush grid place-items-center"><i data-lucide="x"></i></button></div><nav class="mt-10 grid gap-2">${links.map(([n,u])=>`<a data-menu-link href="${u}" class="rounded-2xl px-4 py-4 font-semibold hover:bg-blush hover:text-pink transition">${n}</a>`).join('')}<a data-menu-link href="login.html" class="rounded-2xl px-4 py-4 font-semibold hover:bg-blush hover:text-pink transition">Login / Sign up</a></nav><div class="mt-8 rounded-3xl bg-berry p-5 text-white"><i data-lucide="sparkles" class="text-champagne"></i><p class="display mt-3 text-xl">Your crown. Your statement.</p><p class="mt-2 text-xs text-white/65">Premium hair, selected with intention.</p></div></div></div>`}
function siteFooter(){
const socials=[
  {name:'Instagram',href:'https://www.instagram.com/',icon:'instagram',label:'Instagram'},
  {name:'Facebook',href:'https://www.facebook.com/',icon:'facebook',label:'Facebook'},
  {name:'TikTok',href:'https://www.tiktok.com/',icon:'music-2',label:'TikTok'},
  {name:'WhatsApp',href:'https://wa.me/',icon:'message-circle',label:'WhatsApp'}
];
   return `<footer class="bg-[#241019] text-white mt-20"><div class="max-w-7xl mx-auto px-2 sm:px-6 py-8 sm:py-14 grid grid-cols-4 gap-2 sm:gap-10"><div><div class="display text-sm sm:text-2xl font-bold">Hair by <i class="text-pink">Sentle</i></div><p class="mt-2 sm:mt-4 text-[8px] sm:text-sm leading-4 sm:leading-6 text-white/55">Premium hair and weave collections designed to make every look feel personal.</p><div class="mt-3 sm:mt-5 flex flex-wrap gap-1 sm:gap-2">${socials.map(s=>`<a href="${s.href}" target="_blank" rel="noopener noreferrer" aria-label="HairBySentle on ${s.label}" title="${s.label}" class="size-6 sm:size-10 rounded-full bg-white/10 grid place-items-center hover:bg-pink hover:-translate-y-1 transition duration-300"><i data-lucide="${s.icon}" class="size-3 sm:size-4"></i></a>`).join('')}</div><p class="mt-2 sm:mt-3 text-[7px] sm:text-[10px] leading-3 text-white/30">Social links are ready — replace the platform URLs with HairBySentle's exact accounts.</p></div><div><h3 class="text-[10px] sm:text-base font-bold">Shop</h3><div class="mt-2 sm:mt-4 grid gap-2 sm:gap-3 text-[8px] sm:text-sm text-white/55"><a class="hover:text-white transition" href="shop.html">All products</a><a class="hover:text-white transition" href="collections.html">Collections</a><a class="hover:text-white transition" href="checkout.html">Checkout</a></div></div><div><h3 class="text-[10px] sm:text-base font-bold">Help</h3><div class="mt-2 sm:mt-4 grid gap-2 sm:gap-3 text-[8px] sm:text-sm text-white/55"><a class="hover:text-white transition" href="contact.html">Contact us</a><a class="hover:text-white transition" href="installations.html">Installations</a><a class="hover:text-white transition" href="about.html">About us</a></div></div><div><h3 class="text-[10px] sm:text-base font-bold">Stay in the loop</h3><p class="mt-2 sm:mt-4 text-[8px] sm:text-sm leading-4 sm:leading-6 text-white/55">Get updates on new drops and special offers.</p><form onsubmit="event.preventDefault();toast('Thanks — you are on the list!')" class="mt-2 sm:mt-4 flex rounded-full bg-white/10 p-0.5 sm:p-1"><input required type="email" class="min-w-0 w-0 flex-1 bg-transparent px-1 sm:px-4 text-[8px] sm:text-sm outline-none text-white placeholder:text-white/40" placeholder="Your email" aria-label="Email address"><button class="rounded-full bg-pink px-1.5 sm:px-4 py-1 sm:py-2 text-[8px] sm:text-xs font-bold hover:bg-white hover:text-berry transition">Join</button></form></div></div><div class="border-t border-white/10 py-3 sm:py-5 text-center text-[8px] sm:text-xs text-white/35">© 2026 HairBySentle. All Rights Reserved.</div></footer>`
}
function cartMarkup(){return `<div id="cartDrawer" class="drawer hidden fixed inset-0 z-[90]"><div data-cart-close class="absolute inset-0 bg-black/35"></div><aside class="drawer-panel absolute right-0 top-0 h-full w-full sm:max-w-md bg-white flex flex-col shadow-2xl"><div class="p-5 border-b border-rose flex items-center justify-between"><div><p class="text-xs uppercase tracking-[.18em] text-pink font-bold">Shopping bag</p><h2 class="display text-2xl font-semibold">Your selections</h2></div><button data-cart-close class="size-10 rounded-full bg-blush grid place-items-center"><i data-lucide="x"></i></button></div><div id="cartItems" class="flex-1 overflow-y-auto px-5"></div><div class="p-5 border-t border-rose"><div class="flex justify-between font-bold"><span>Total</span><span id="cartTotal">R0</span></div><a href="checkout.html" class="btn mt-4 w-full rounded-full bg-berry py-3.5 text-center text-sm font-bold text-white block">Continue to checkout <i data-lucide="arrow-right" class="inline size-4 ml-1"></i></a></div></aside></div>`}
